### ISSUE TITLE
As github user I install the FundRequest browser plugin from the Chrome store

### ISSUE THREAD

**Issue by gerbert-vandenberghe** [FundRequest/chrome-browser-plugin#1]
#### Context

Chrome browser plugins have to be installed from the chrome web store. The goal of this story is to make the FundRequest-Github browserplugin available on the chrome web store.

#### Flow of events

1. The user navigates to the chrome web store.
2. The user searches for the FundRequest-Github browserplugin.
3. The user installs the FundRequest-Github browserplugin.
4. The user opens the FundRequest-Github browserplugin.
5. The user sees the funding on Github issues when using the FundRequest-Github browserplugin.

#### Testcases

- Testcase: A user has installed the FundRequest-Github browserplugin. The user surfs on Github and there are funded issues displayed.
-- Result: The user sees the funding on issues.

**Comment by gerbert-vandenberghe** [comment]
@Simsteve7 This issue has status 'ready to test'. Is this correct, since I cannot find the plugin on the chome webstore.

**Comment by davy-vr** [comment]
Currently possible by using the direct url, it is not visible yet in the chrome store itself
