### ISSUE TITLE
Chrome extension doesn't load when an issue is funded in a different token then FND

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/chrome-browser-plugin#27]
At the moment it seems that the chrome ext. can't handle other ERC20 tokens

**Issue funded with XUC**
![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/303d1e06-49b1-4c28-9c4b-1510f7d6e064)

**Issue funded in FND**
![image.png](https://images.zenhubusercontent.com/5a8ee19b4b5806bc2bc7fc92/9b357fcc-381d-499a-8fb8-d50885c152ae)

**Comment by nico-ptrs** [comment]
The bug is in
https://github.com/FundRequest/chrome-browser-plugin/blob/aeebd5de7cf15e2501a104dcd124b02d4964ccbc/src/classes/models/RequestFunds.ts

Here, funds.fndFunds will be null when only funded with 'other' token

**Comment by karelstriegel** [comment]
Tested and passed  
![image](https://user-images.githubusercontent.com/6882032/42597289-945bf584-8558-11e8-91c4-3a1a93de7c29.png)
