### ISSUE TITLE
Update TST1 FundRequestContract address in the browser plugin (migration was performed)

### ISSUE THREAD

**Issue by karelstriegel** [FundRequest/chrome-browser-plugin#33]
Migration is done, newest FundRequestContract for Test environment = 0x55356bccfa48d09dc824c0aea6ebd868ff5edf50

Please also remove the development env and add the testing env (tst1) to the browser extention available envs

**Comment by davy-vr** [comment]
Contract address will be pulled from the live environment.
Make sure the latest version is online at the test environment and restart chrome (or enable/disable the extension)
