### ISSUE TITLE
As github user I add funding to a Gihub issue from the browser plugin

### ISSUE THREAD

**Issue by gerbert-vandenberghe** [FundRequest/chrome-browser-plugin#4]
#### Context
 
In previous stories we already added the functionality to use a Chrome browser plugin to view the funding on Github issues. The goal of this story is to make it possible to fund an issue from within the plugin as well.

#### Prerequisites

- The user has installed the FundRequest browser plugin for Github.
- The user has installed the Metamask plugin.

#### Flow of events

1. The funder navigates to the detail page of a Github issue.
2. The funder chooses to fund the issue.
3. A new tab is opened an goes to the wizard ready to fund the request. As much detail as possible is prefilled in into the wizard

**Comment by karelstriegel** [comment]
Related https://github.com/FundRequest/platform/pull/59

**Comment by gerbert-vandenberghe** [comment]
@nicohaelterman can you review plz?
